// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/shamer/Receiver.tsx": () => import("../components/mockups/shamer/Receiver.tsx"),
  "./components/mockups/shamer/Sender.tsx": () => import("../components/mockups/shamer/Sender.tsx")
};
